export const ADD_TODO = "ADD_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const ADD_TAG = "ADD_TAG"
export const UPDATE_TAG = "UPDATE_TAG"
export const DELETE_TAG = "DELETE_TAG"
